// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Archive struct {
	ID        int64  `json:"id"`
	Filename  string `json:"filename"`
	Editorial string `json:"editorial"`
	CoverPage int64  `json:"cover_page"`
	Favorite  bool   `json:"favorite"`
	CreatedAt string `json:"created_at"`
}
