// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: querys.sql

package database

import (
	"context"
	"database/sql"
)

const getArchive = `-- name: GetArchive :one
SELECT id, filename FROM archive_schema.archive WHERE id = $1
`

type GetArchiveRow struct {
	ID       int32  `json:"id"`
	Filename string `json:"filename"`
}

func (q *Queries) GetArchive(ctx context.Context, dollar_1 sql.NullInt32) (GetArchiveRow, error) {
	row := q.db.QueryRowContext(ctx, getArchive, dollar_1)
	var i GetArchiveRow
	err := row.Scan(&i.ID, &i.Filename)
	return i, err
}
