// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package database

import (
	"context"
)

const getArchive = `-- name: GetArchive :one
SELECT id, filename FROM archive_schema.archive WHERE id = $1
`

type GetArchiveRow struct {
	ID       int32  `json:"id"`
	Filename string `json:"filename"`
}

func (q *Queries) GetArchive(ctx context.Context, id int32) (GetArchiveRow, error) {
	row := q.db.QueryRowContext(ctx, getArchive, id)
	var i GetArchiveRow
	err := row.Scan(&i.ID, &i.Filename)
	return i, err
}

const getArchiveByName = `-- name: GetArchiveByName :one
SELECT filename FROM archive_schema.archive WHERE filename=name
`

func (q *Queries) GetArchiveByName(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getArchiveByName)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}
