// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const archiveExists = `-- name: ArchiveExists :one
SELECT
  1
FROM archive
WHERE id = ?
`

func (q *Queries) ArchiveExists(ctx context.Context, id int) (int64, error) {
	row := q.db.QueryRowContext(ctx, archiveExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE
FROM archive 
WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id int) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getAllFiles = `-- name: GetAllFiles :many
SELECT
  id,
  filename
FROM archive
`

type GetAllFilesRow struct {
	ID       int    `json:"id"`
	Filename string `json:"filename"`
}

func (q *Queries) GetAllFiles(ctx context.Context) ([]GetAllFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFilesRow
	for rows.Next() {
		var i GetAllFilesRow
		if err := rows.Scan(&i.ID, &i.Filename); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchive = `-- name: GetArchive :one
SELECT id, filename, editorial, cover_page, favorite, created_at FROM archive WHERE id = ? LIMIT 1
`

func (q *Queries) GetArchive(ctx context.Context, id int) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchive, id)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Editorial,
		&i.CoverPage,
		&i.Favorite,
		&i.CreatedAt,
	)
	return i, err
}

const getArchiveById = `-- name: GetArchiveById :one
SELECT filename FROM archive WHERE id = ?
`

func (q *Queries) GetArchiveById(ctx context.Context, id int) (string, error) {
	row := q.db.QueryRowContext(ctx, getArchiveById, id)
	var filename string
	err := row.Scan(&filename)
	return filename, err
}

const getArchiveByName = `-- name: GetArchiveByName :one
SELECT id, filename, editorial, cover_page, favorite, created_at FROM archive WHERE filename = ? LIMIT 1
`

func (q *Queries) GetArchiveByName(ctx context.Context, filename string) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveByName, filename)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Editorial,
		&i.CoverPage,
		&i.Favorite,
		&i.CreatedAt,
	)
	return i, err
}

const getArchivePage = `-- name: GetArchivePage :many
SELECT
  id,
  filename,
  editorial,
  favorite
FROM archive
ORDER BY favorite DESC, id
LIMIT ?
OFFSET ?
`

type GetArchivePageParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type GetArchivePageRow struct {
	ID        int    `json:"id"`
	Filename  string `json:"filename"`
	Editorial string `json:"editorial"`
	Favorite  bool   `json:"favorite"`
}

func (q *Queries) GetArchivePage(ctx context.Context, arg GetArchivePageParams) ([]GetArchivePageRow, error) {
	rows, err := q.db.QueryContext(ctx, getArchivePage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArchivePageRow
	for rows.Next() {
		var i GetArchivePageRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Editorial,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountArchive = `-- name: GetCountArchive :one
SELECT
  count(id)
FROM archive
`

func (q *Queries) GetCountArchive(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCountArchive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCountSearch = `-- name: GetCountSearch :one
SELECT
  count(id)
FROM archive
WHERE filename LIKE '%' || ? || '%'
`

func (q *Queries) GetCountSearch(ctx context.Context, dollar_1 sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCountSearch, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO archive(
  filename,
  editorial
)
VALUES(?, ?)
RETURNING id
`

type InsertFileParams struct {
	Filename  string `json:"filename"`
	Editorial string `json:"editorial"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (int, error) {
	row := q.db.QueryRowContext(ctx, insertFile, arg.Filename, arg.Editorial)
	var id int
	err := row.Scan(&id)
	return id, err
}

const searchArchive = `-- name: SearchArchive :many
SELECT
  id,
  filename,
  editorial,
  favorite
FROM archive
WHERE filename LIKE '%' || ? || '%'
ORDER BY favorite DESC, id
LIMIT ?
OFFSET ?
`

type SearchArchiveParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int64          `json:"limit"`
	Offset  int64          `json:"offset"`
}

type SearchArchiveRow struct {
	ID        int    `json:"id"`
	Filename  string `json:"filename"`
	Editorial string `json:"editorial"`
	Favorite  bool   `json:"favorite"`
}

func (q *Queries) SearchArchive(ctx context.Context, arg SearchArchiveParams) ([]SearchArchiveRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArchive, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArchiveRow
	for rows.Next() {
		var i SearchArchiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Editorial,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEditFile = `-- name: SetEditFile :exec
UPDATE
  archive
SET
  filename = ?,
  editorial = ?
WHERE id = ?
`

type SetEditFileParams struct {
	Filename  string `json:"filename"`
	Editorial string `json:"editorial"`
	ID        int    `json:"id"`
}

func (q *Queries) SetEditFile(ctx context.Context, arg SetEditFileParams) error {
	_, err := q.db.ExecContext(ctx, setEditFile, arg.Filename, arg.Editorial, arg.ID)
	return err
}

const setFavorite = `-- name: SetFavorite :exec
UPDATE archive
SET favorite = ?
WHERE id = ?
`

type SetFavoriteParams struct {
	Favorite bool `json:"favorite"`
	ID       int  `json:"id"`
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, setFavorite, arg.Favorite, arg.ID)
	return err
}
