// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateArchiveTable(ctx context.Context) error
	CreateSchema(ctx context.Context) error
	GetArchive(ctx context.Context, id int32) (ArchiveSchemaArchive, error)
	GetArchiveByName(ctx context.Context) (string, error)
	GetArchivePage(ctx context.Context, arg GetArchivePageParams) ([]GetArchivePageRow, error)
	GetCountArchive(ctx context.Context) (int64, error)
	GetCountSearch(ctx context.Context, dollar_1 sql.NullString) (int64, error)
	GetThumbnails(ctx context.Context) ([]GetThumbnailsRow, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (int32, error)
	SaveThumbnail(ctx context.Context, arg SaveThumbnailParams) error
	SearchArchive(ctx context.Context, arg SearchArchiveParams) ([]SearchArchiveRow, error)
	SetEditFile(ctx context.Context, arg SetEditFileParams) error
	SetFavorite(ctx context.Context, arg SetFavoriteParams) error
}

var _ Querier = (*Queries)(nil)
