// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	ArchiveExists(ctx context.Context, id int) (int64, error)
	DeleteFile(ctx context.Context, id int) error
	GetAllFiles(ctx context.Context) ([]GetAllFilesRow, error)
	GetArchive(ctx context.Context, id int) (Archive, error)
	GetArchiveById(ctx context.Context, id int) (string, error)
	GetArchiveByName(ctx context.Context, filename string) (Archive, error)
	GetArchivePage(ctx context.Context, arg GetArchivePageParams) ([]GetArchivePageRow, error)
	GetCountArchive(ctx context.Context) (int, error)
	GetCountSearch(ctx context.Context, dollar_1 sql.NullString) (int, error)
	InsertFile(ctx context.Context, arg InsertFileParams) (int, error)
	SearchArchive(ctx context.Context, arg SearchArchiveParams) ([]SearchArchiveRow, error)
	SetEditFile(ctx context.Context, arg SetEditFileParams) error
	SetFavorite(ctx context.Context, arg SetFavoriteParams) error
}

var _ Querier = (*Queries)(nil)
