FROM nginx:alpine

RUN apk add --no-cache curl unzip

RUN curl -L https://github.com/mozilla/pdf.js/releases/download/v5.4.530/pdfjs-5.4.530-legacy-dist.zip \
    -o /tmp/pdfjs.zip \
 && unzip /tmp/pdfjs.zip -d /usr/share/nginx/html \
 && rm /tmp/pdfjs.zip

EXPOSE 80
